//Import area
import React from 'react'
import Header from './Header'
import LeftAside from './LeftAside'
import RightAside from './RightAside'
import Footer from './Footer'
import Head from 'next/head'

//Defenation area
export default function CommonLayouts({children}) {
  return (
    <>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='container-fluid'>
      <Header></Header>

      <main className='row m-0 g_tbdr'>

        <LeftAside></LeftAside>

        {children} 
        

        <RightAside></RightAside>
      </main>
      <Footer></Footer>
    </div>
    </>
  )
}

//Export area